#
# Spiderfoot Dockerfile (Full - includes all CLI tools, etc.)
#
# http://www.spiderfoot.net
#
# Written by: kost

FROM python:3
WORKDIR /tools
ENV SPIDERFOOT_DATA=/var/lib/spiderfoot SPIDERFOOT_LOGS=/var/lib/spiderfoot/log SPIDERFOOT_CACHE=/var/lib/spiderfoot/cache SPIDERFOOT_CONFIG_DIR=/configs VIRTUAL_ENV="/opt/venv"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
# Install tools/dependencies from apt
RUN apt-get -y update && apt-get -y install nbtscan onesixtyone nmap libcap2-bin && \
 setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap && \
 mkdir -p /tools && \
 apt-get -y install ruby ruby-dev bundler && \
 git clone https://github.com/urbanadventurer/WhatWeb && \
 gem install rchardet mongo json && cd /tools/WhatWeb && \
 bundle install && cd /tools && \
 groupadd spiderfoot && \
 useradd -m -g spiderfoot -d /home/spiderfoot -s /sbin/nologin -c "SpiderFoot User" spiderfoot && \
 apt remove -y cmdtest \
    && apt remove -y yarn \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo 'deb https://dl.yarnpkg.com/debian/ stable main' |tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install yarn -y \
    && yarn install \
    && curl -fsSL https://deb.nodesource.com/setup_17.x | bash - \
    # && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs npm \
    && npm install -g retire && \
 wget -qO - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list \
    && apt -y update && apt install --allow-unauthenticated -y google-chrome-stable && \
 wget https://github.com/projectdiscovery/nuclei/releases/download/v2.9.15/nuclei_2.9.15_linux_amd64.zip \
    && unzip nuclei_2.9.15_linux_amd64.zip \
    && git clone https://github.com/projectdiscovery/nuclei-templates.git && \
 apt-get install -y bsdmainutils dnsutils coreutils && \
 git clone https://github.com/drwetter/testssl.sh.git && \
 pip3 install snallygaster trufflehog && \
 mkdir -p $SPIDERFOOT_DATA $SPIDERFOOT_LOGS $SPIDERFOOT_CACHE && \
 chown spiderfoot:spiderfoot $SPIDERFOOT_DATA $SPIDERFOOT_LOGS $SPIDERFOOT_CACHE && \
 mkdir -p "$VIRTUAL_ENV"
 
WORKDIR /home/spiderfoot
COPY . .
RUN python -m venv "$VIRTUAL_ENV"
ARG REQUIREMENTS=requirements.txt
COPY "$REQUIREMENTS" requirements.txt

RUN chown -R spiderfoot:spiderfoot /tools "$VIRTUAL_ENV" "/home/spiderfoot"
USER spiderfoot

RUN pip install -U pip && pip install -r "$REQUIREMENTS" && \
 pip install dnstwist && \
 cd /tools && \
 git clone https://github.com/Tuhinshubhra/CMSeeK && cd CMSeeK && \
 pip install -r requirements.txt && mkdir Results && \
 git clone https://github.com/EnableSecurity/wafw00f && \
 cd wafw00f && \
 python3 setup.py install && \
 echo "done"

WORKDIR /home/spiderfoot

EXPOSE 5001

# Run the application
CMD mkdir -p $SPIDERFOOT_DATA $SPIDERFOOT_LOGS $SPIDERFOOT_CACHE && chown -R spiderfoot:spiderfoot $SPIDERFOOT_DATA $SPIDERFOOT_LOGS $SPIDERFOOT_CACHE && ./sfconf.py -f '' -i '' -c '' -j \
 '{ \
    "sfp_tool_dnstwist:dnstwistpath": "/opt/venv/bin/dnstwist", \
    "sfp_tool_cmseek:cmseekpath": "/tools/CMSeeK/cmseek.py", \
    "sfp_tool_whatweb:whatweb_path": "/tools/WhatWeb/whatweb", \
    "sfp_tool_wafw00f:wafw00f_path": "/opt/venv/bin/wafw00f", \
    "sfp_tool_onesixtyone:onesixtyone_path": "/usr/bin/onesixtyone", \
    "sfp_tool_retirejs:retirejs_path": "/usr/bin/retire", \
    "sfp_tool_testsslsh:testsslsh_path": "/tools/testssl.sh/testssl.sh", \
    "sfp_tool_snallygaster:snallygaster_path": "/usr/local/bin/snallygaster", \
    "sfp_tool_trufflehog:trufflehog_path": "/usr/local/bin/trufflehog", \
    "sfp_tool_nuclei:nuclei_path": "/tools/nuclei", \
    "sfp_tool_nuclei:template_path": "/tools/nuclei-templates", \
    "sfp_tool_wappalyzer:wappalyzer_path": "/tools/wappalyzer/src/drivers/npm/cli.js", \
    "sfp_tool_nbtscan:nbtscan_path": "/usr/bin/nbtscan" \
 }' || true && ./sfconf.py && python ./sf.py -l 0.0.0.0:5001
